# mmstream/connection
INTERFACES=Connection  
CLASSES=
ABSTRACT_CLASSES=Connection_Exception
SUBPACKAGES=ip
EXCEPTION=Connection_Exception

include ../Makefile.standard_rules
include ../Makefile.local
