# mmstream/protocols/rtp
INTERFACES=
CLASSES= RTP_SeqNum_Registration  RTP_SenderStatistics RTP_ReceptionStatistics RTP_LocalSource RTP_RemoteSource RTP_SourceTable RTP_Receiver_Thread RTCP_Sender_Thread RTCP_Receiver_Thread RTP_CoDec
ABSTRACT_CLASSES= RTProtocol RTCProtocol
SUBPACKAGES=NO
EXCEPTIONS=RTP_Exception RTCP_Exception

include ../../Makefile.local
include ../../Makefile.standard_rules
