# mmstream/address
INTERFACES= Address 
CLASSES=IP_Address
#CLASSES=UDP_Address TCP_Address UDP_Multicast_Address UDP_Unicast_Address
ABSTRACT_CLASSES=
SUBPACKAGES=NO
EXCEPTIONS=Address_Exception
include ../Makefile.standard_rules
include ../Makefile.local
