# mmstream/connection/ip

SUBPACKAGES=NO
INTERFACES= 
ABSTRACT_CLASSES=IP_Connection
CLASSES=IP_Connection_Exception UDP_Connection UDP_Multicast_Connection 
EXCEPTION=UDP_Connection_Exception UDP_Multicast_Connection_Exception

include ../../Makefile.local
include ../../Makefile.standard_rules
