# mmstream/util 
#INTERFACES=Marshallable Output Clock Master_Clock
INTERFACES=Output Clock Master_Clock
CLASSES=Chunk TimedObject \
	Lock \
	Counter \
	ClockSyncData 	ClockSetData \
	NTPTimeStamp	NTP_Clock	NTP_Master_Clock \
	SeqNum_Generator  		SeqNum_Registerer \
	Chunk_Queue 	Object_Queue \
	Println_Output	
#	SourceTable \
#	Println_Output	Println_SessionOutput	Println_SourceOutput	Println_StreamOutput \
#	SenderStatistics		ReceptionStatistics
#ABSTRACT_CLASSES=Source	RemoteSource	OwnSource Queue
ABSTRACT_CLASSES=Queue
PACKAGES=
EXCEPTIONS=Base_Exception Chunk_Exception
SUBPACKAGES=NO

include ../Makefile.local
include ../Makefile.standard_rules
