# mmstream/stream
INTERFACES=Stream StreamExporter StreamManager StreamOutput
ABSTRACT_CLASSES=
CLASSES=StreamBase \
	Chunk_Stream \
	MemoryImageSource_Stream \
	TOMS_StreamManager \
	Println_StreamOutput
SUBPACKAGES=NO
EXCEPTIONS=Stream_Exception

include ../Makefile.local
include ../Makefile.standard_rules
