# mmstream/source
INTERFACES=SourceOutput
CLASSES=SourceTable \
	Println_SourceOutput \
	SenderStatistics	ReceptionStatistics
ABSTRACT_CLASSES=Source		RemoteSource	LocalSource 
PACKAGES=
EXCEPTIONS=
SUBPACKAGES=NO

include ../Makefile.local
include ../Makefile.standard_rules
