# mmstream/producer
INTERFACES=ProducerOutput ProducerControl
CLASSES=Byte_Producer 	\
	File_Producer 	\
	Println_ProducerOutput
ABSTRACT_CLASSES=ProducerBase
SUBPACKAGES=NO
EXCEPTIONS=

include ../Makefile.local
include ../Makefile.standard_rules
