## mmstream top Makefile

SUBPACKAGES=util address source connection protocols config stream gui apps session consumer producer main
CLASSES=
ABSTRACT_CLASSES=
INTERFACES=
EXCEPTIONS=

include ./Makefile.local
include ./Makefile.standard_rules


