# mmstream/gui
INTERFACES=GuiManager \
	ProtocolCoDecOptions \
	PayloadTypeOptions \
	ConnectionOptions \
	SessionMapperOptions \
	ProducerOptions ConsumerOptions 

CLASSES=Byte_ProducerOptions 	Byte_ConsumerOptions \
	File_ProducerOptions 	File_ConsumerOptions \
	StreamSyncDialog \
	Image_ConsumerOptions \
	ByteTest_PayloadTypeOptions 	RGB8_PayloadTypeOptions		RGB24_PayloadTypeOptions \
	TOMS_SessionMapperOptions \
	RTP_ProtocolCoDecOptions 		\
	UDP_ConnectionOptions		UDP_Multicast_ConnectionOptions \
	ConnectionPanel		\
	RTP_Remote_SenderStatistics_Panel	RTP_Local_SenderStatistics_Panel \
	RTP_ReceptionStatistics_Panel	RTP_ReceptionStatistics_DataPanel	RTP_ReceptionStatistics_LabelPanel \
	Producer_Dialog \
	Consumer_Dialog \
	LocalSource_Dialog 		RemoteSource_Dialog \
	Session_Dialog		\
	ProtoSession_Dialog \
	NewSession_Dialog \
	NewProducer_Dialog		NewConsumer_Dialog \
	ExportImport_Dialog \
	MainFrame 	\
	TOMS_GuiManager


ABSTRACT_CLASSES=SenderStatistics_Panel \
		 ReceptionStatistics_Panel \
		 ReceptionStatistics_DataPanel	 ReceptionStatistics_LabelPanel 

SUBPACKAGES=NO

EXCEPTIONS=Gui_Exception

include ../Makefile.local
include ../Makefile.standard_rules
