# mmstream/consumer
INTERFACES=ConsumerOutput ConsumerControl
CLASSES=Byte_Consumer \
	ImageCanvas \
	Image_Consumer \
	File_Consumer \
	Println_ConsumerOutput 
ABSTRACT_CLASSES=ConsumerBase
SUBPACKAGES=NO
EXCEPTIONS=

include ../Makefile.local
include ../Makefile.standard_rules
