# mmstream/config
INTERFACES=TypeConfiguration ProdConsConfiguration
CLASSES=Config \
	RTP_Profile \
	Type	TypeHandler	TypeHandlerTable	PayloadType \
	Connection_TypeConfiguration \
	SessionMapper_TypeConfiguration \
	Address_TypeConfiguration \
	ProtocolCoDec_TypeConfiguration \
	Payload_TypeConfiguration \
	Producer_TypeConfiguration \
	Consumer_TypeConfiguration
ABSTRACT_CLASSES=Profile 
	
SUBPACKAGES=NO
EXCEPTIONS=Config_Exception

include ../Makefile.local
include ../Makefile.standard_rules
